# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: true
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.1
matrix:
  allow_failures:

notifications:
  email: false

script:
  - julia --color=yes --check-bounds=yes -e 'using Pkg; Pkg.add("Test"); Pkg.add("BenchmarkTools"); Pkg.add("SpecialFunctions"); Pkg.update(); Pkg.test("SeriesAccelerators", coverage=true)'


after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("SeriesAccelerators")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

